# https://taskfile.dev
version: '3'
vars:
  BINFILE: ratelimiter
  IMG: sgaunet/ratelimiter:latest

tasks:

  default:
    desc: "List all available tasks"
    cmds:
      - task -a

  build:
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .

  install-prereq:
    cmds:
      - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/kisielk/errcheck@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  # install hooks
  install-pre-commit:
    cmds:
      - pre-commit install

  pre-commit:
    cmds:
      - pre-commit run --all-files


  image:
    deps: 
    - default
    # sources:
    #   - ./**/*
    cmds:
      - docker build . -t {{.IMG}}
      - docker push {{.IMG}}

  load-test:
    dir: tst/load-test
    cmds:
      - ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | grep -v '^172' | tail -1 > ip.txt
      - echo "GET http://$(cat ip.txt):1337" > targets.txt
      - vegeta attack -duration="300s" -rate="300" -targets="targets.txt" -output=attack.bin
      - vegeta plot -title="ratelimiter" attack.bin > "result.html"

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean