version: '3.2'
services:
    echo:
        image: sgaunet/http-echo:latest
        # ports:
        #     - 5678:8080
        network_mode: "host"

    ratelimiter:
      image: sgaunet/ratelimiter:latest
      ports:
        - 1337:1337
      volumes:
        - ./conf.yaml:/conf.yaml
      command: /ratelimiter -c /conf.yaml
      network_mode: "host"
